"use strict";
exports.__esModule = true;
exports.app = void 0;
var express = require('express');
var bodyParser = require('body-parser');
var cors = require('cors');
var path = require('path');
var v2Routes = require('./routes/v2');
var v1Routes = require('./routes/v1');
exports.app = express();
exports.app.use(cors());
exports.app.use(bodyParser.urlencoded({ extended: false }));
exports.app.use(bodyParser.json());
exports.app.use(express.static(path.join(__dirname, '/')));
exports.app.use('/', v1Routes);
exports.app.use('/v2', v2Routes);
exports.app.listen(process.env.PORT || 5000);
