export const REGISTRY = [
  {
    id: 1,
    title: 'Introduction',
    urlTitle: 'introduction',
    path: 'assets/docs/intro/README.md',
  },
  {
    id: 2,
    title: 'About',
    urlTitle: 'about',
    path: 'assets/docs/about/README.md',
  },
  {
    id: 3,
    title: 'FAQ',
    urlTitle: 'faq',
    path: 'assets/docs/faq/README.md',
  },
  {
    id: 4,
    title: 'Data Format',
    urlTitle: 'data-format',
    path: 'assets/docs/data-format/README.md',
  },
  {
    id: 5,
    title: 'Visualization',
    urlTitle: 'visualization',
    path: 'assets/docs/visualization/README.md',
  },
  {
    id: 6,
    title: 'Visualization Functions',
    urlTitle: 'visualization-functions',
    path: 'assets/docs/vis-functions/README.md',
  },
  {
    id: 7,
    title: 'Visualization Controls',
    urlTitle: 'visualization-controls',
    path: 'assets/docs/vis-controls/README.md',
  },
  {
    id: 8,
    title: 'Compare',
    urlTitle: 'compare',
    path: 'assets/docs/compare/README.md',
  },
  {
    id: 9,
    title: 'Playground',
    urlTitle: 'playground',
    path: 'assets/docs/playground/README.md',
  },
  {
    id: 10,
    title: 'Report',
    urlTitle: 'report',
    path: 'assets/docs/report/README.md',
  },
  {
    id: 11,
    title: 'Indented List',
    urlTitle: 'indented-list',
    path: 'assets/docs/indented-list/README.md',
  },
  {
    id: 12,
    title: 'Search',
    urlTitle: 'search',
    path: 'assets/docs/search/README.md',
  },
  {
    id: 13,
    title: 'Debug Log',
    urlTitle: 'debug-log',
    path: 'assets/docs/log/README.md',
  },
  {
    id: 14,
    title: 'Export',
    urlTitle: 'export',
    path: 'assets/docs/export/README.md',
  },
  {
    id: 14,
    title: 'ASCT+B API',
    urlTitle: 'api',
    path: 'assets/docs/asct+b-api/README.md',
  },
];
